# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra'
gem 'payabli', '2.2.26'
gem 'thin'
gem 'dotenv'

group :development do
  gem 'rerun'
end
gem "rackup", "~> 2.2"
gem "puma", "~> 7.1"
